"""Deterministic, fail-closed proactive pipeline contracts."""

from telegram_userbot.domain.proactive.budget import BudgetLedger
from telegram_userbot.domain.proactive.jobs import DueJob, DueJobState, DurableDueJobStore
from telegram_userbot.domain.proactive.models import (
    AgentDecision,
    BudgetLimits,
    BudgetReservation,
    Candidate,
    CandidateState,
    ContactSettings,
    OccurrenceState,
    ProactiveAction,
    ProactiveContext,
    ProactivePolicy,
    ReasonCode,
    RelationshipLevel,
    ReservationState,
    RuleOccurrence,
    SuppressionReason,
    TypedEvidence,
)
from telegram_userbot.domain.proactive.pipeline import (
    AuthorizationInput,
    FinalGateInput,
    ProactiveTarget,
    build_text_only_context,
    final_gate,
    map_mode,
    preliminary_gate,
)
from telegram_userbot.domain.proactive.rules import (
    ExplicitFollowupFact,
    FilterResult,
    IntentionFact,
    LifeEventFact,
    RelationshipFact,
    aggregate_candidates,
    filter_occurrences,
    materialize_explicit_followup,
    materialize_intention,
    materialize_life_event,
    materialize_reconnect,
)
from telegram_userbot.domain.proactive.validation import (
    ProactiveValidationError,
    parse_agent_decision,
    parse_agent_response_json,
)

__all__ = [
    "AgentDecision",
    "AuthorizationInput",
    "BudgetLedger",
    "BudgetLimits",
    "BudgetReservation",
    "Candidate",
    "CandidateState",
    "ContactSettings",
    "DueJob",
    "DueJobState",
    "DurableDueJobStore",
    "ExplicitFollowupFact",
    "FilterResult",
    "FinalGateInput",
    "IntentionFact",
    "LifeEventFact",
    "OccurrenceState",
    "ProactiveAction",
    "ProactiveContext",
    "ProactivePolicy",
    "ProactiveTarget",
    "ProactiveValidationError",
    "ReasonCode",
    "RelationshipFact",
    "RelationshipLevel",
    "ReservationState",
    "RuleOccurrence",
    "SuppressionReason",
    "TypedEvidence",
    "aggregate_candidates",
    "build_text_only_context",
    "filter_occurrences",
    "final_gate",
    "map_mode",
    "materialize_explicit_followup",
    "materialize_intention",
    "materialize_life_event",
    "materialize_reconnect",
    "parse_agent_decision",
    "parse_agent_response_json",
    "preliminary_gate",
]
